docs: fix typos
karlicoss/HPI pull request #281
Opened 2023-03-26 09:13 UTC by kianmeng

found via `codespell -L copie,datas,pres,fo,tooks,noo,ue,ket,frop`

2023-03-27 00:31 UTC, karlicoss requested changes
thanks! a few comments

2023-03-27 00:31 UTC, karlicoss commented on misc/check-twitter.sh
> +# archive isn't explaining images by default
think that was meant to be "expanding"

2023-03-27 00:31 UTC, karlicoss commented on my/core/kompress.py
> +    # since when we can .read_text, encoding is passed already
think that was meant to be "call"

2023-03-27 00:31 UTC, karlicoss commented on my/photos/main.py
> +            raise RuntimeError(f'Weird path {self.path}, can't match against anything')
need to change outer quotes to double quotes, otherwise we get syntax error

2023-03-27 02:02 UTC, merged

2023-03-29 01:46 UTC, kianmeng commented
:tada: :tada: :tada: :tada: :tada: